### PR TITLE
Fixes ErrorException in Laravel 5.5

### PR DESCRIPTION
**Pull request by whoacowboy**
[ErrorException]
  Declaration of BackupManager\Laravel\Laravel55Compatibility::table($headers, $rows, $style = 'default') should be compati
  ble with Illuminate\Console\Command::table($headers, $rows, $tableStyle = 'default', array $columnStyles = Array)

### CODE REVIEW

**Comment by cotcotquedec** [comment]
I need this!! ;-)

**Comment by SergeyMiracle** [comment]
What are we waiting for? 🤔

**Comment by 4sh3** [comment]
I need too, :D

**Comment by ShawnMcCool** [comment]
I merged it in, please consider including the package with dev-master and ensuring that it works fine. Then, I'll tag a new release. Thanks for the PR. =)

**Comment by SergeyMiracle** [comment]
@ShawnMcCool did update to dev-master, working fine

**Pull request merged**
