### PR TITLE
php7 support

### PR DESCRIPTION
**Pull request by younes0**
composer will now install under php7

### CODE REVIEW

**Comment by rogervila** [comment]
Is not working yet.

captura de pantalla 2015-12-05 a las 13 28 51

**Comment by younes0** [comment]
@rogervila it does :) 
in your composer.json:

``` json
"repositories": [
    { 
        "type": "vcs", 
        "url": "https://github.com/younes0/laravel"
    },
]

"require": {
    "backup-manager/laravel": "dev-patch-1"
}
```

**Comment by rogervila** [comment]
@younes0  thank you!

**Comment by ShawnMcCool** [comment]
Thanks. =)

**Pull request merged**
