### PR TITLE
Removing the process timeout

### PR DESCRIPTION
**Pull request by lflaszlo**

### CODE REVIEW

**Comment by Ralla** [comment]
This!

**Comment by sbilde** [comment]
+1

**Comment by lieberkind** [comment]
:horse:

**Comment by bigslott** [comment]
yes

**Comment by ShawnMcCool** [comment]
Thanks =)

**Comment by Ralla** [comment]
@ShawnMcCool in case you haven't noticed, there's a pull request for L5 as well. 

Are these changes going to be tagged to 1.x.x?

**Pull request merged**
